name: build

on:
  push:
#    branches:
#      - 'main'
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
#      - name: Set up Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: 1.17
#      - name: Cache Go modules
#        uses: actions/cache@v2
#        with:
#          path: ~/go/pkg/mod
#          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
#          restore-keys: |
#            ${{ runner.os }}-go-
#      - name: Test
#        run: go test -race -coverprofile=coverage.txt -covermode=atomic
      - name: Prepare
        id: prep
        run: |
          VERSION=sha-${GITHUB_SHA::8}
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF/refs\/tags\//}
          fi
          BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          PKG=github.com/${{ github.REPOSITORY_OWNER }}/${{ github.event.repository.name }}/pkg
          LDFLAGS="-w -s -X $PKG/version.Version=$VERSION -X $PKG/version.BuildDate=$BUILD_DATE"
          echo ::set-output name=LDFLAGS::${LDFLAGS}
          echo ::set-output name=VERSION::${VERSION}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.REPOSITORY_OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            LDFLAGS=${{ steps.prep.outputs.LDFLAGS }}
          tags: |
            ghcr.io/${{ github.REPOSITORY_OWNER }}/${{ github.event.repository.name }}:${{ steps.prep.outputs.VERSION }}
            ghcr.io/${{ github.REPOSITORY_OWNER }}/${{ github.event.repository.name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max